services:
  app:
    build: .
    container_name: laravel_apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel

networks:
  laravel:
    driver: bridge